### ISSUE TITLE
Can't change server port

### ISSUE THREAD

**Issue by ohhopi** [LibreRead/install#1]
I'm already using port 8080 internally on my setup so LibreRead messes things up. 
All I need is to be able to change the server port. 
I believe the port is hardwired in the server ?
Do I have to build the server myself to change it ? If yes, then how should do it ?

**Comment by mysticmode** [comment]
Sure, I need to keep an environment variable for that. But I can't do this now, will take some time.

If you are curious to try it out now. I would say clone the server repo https://github.com/LibreRead/server

* change the port [here](https://github.com/LibreRead/server/blob/master/server.go#L290)
* compile it in your server and copy the `server` binary to the install repo.
* then run the command source install.sh

That should work. I'm available here https://discord.gg/wHCM7DZ if you want to discuss immediately.

**Comment by ohhopi** [comment]
Compiling the server on the side worked. Thanks !

**Comment by gbraad** [comment]
@mysticmode does an issue/task exist to add the needed env settings?
