### ISSUE TITLE
This repo will grow in size and time to clone

### ISSUE THREAD

**Issue by gbraad** [LibreRead/install#2]
This can be improved by doing a shallow clone:

```diff
- git clone https://github.com/LibreRead/install.git /var/libreread
+ git clone https://github.com/LibreRead/install.git /var/libreread --depth 1
```

### Before

    Cloning into 'install'...
    remote: Counting objects: 1027, done.
    remote: Compressing objects: 100% (69/69), done.
    remote: Total 1027 (delta 48), reused 42 (delta 16), pack-reused 942
    Receiving objects: 100% (1027/1027), 46.91 MiB | 3.21 MiB/s, done.
    Resolving deltas: 100% (473/473), done.

### After

    Cloning into 'install'...
    remote: Counting objects: 559, done.
    remote: Compressing objects: 100% (288/288), done.
    remote: Total 559 (delta 179), reused 517 (delta 162), pack-reused 0
    Receiving objects: 100% (559/559), 14.12 MiB | 2.70 MiB/s, done.
    Resolving deltas: 100% (179/179), done.

## Alternative
Use releases or other way (even githug pages would do) to host the actual binary

**Comment by mysticmode** [comment]
I'll put up a release, then do it like docker does.

`wget -qO- https://get.libreread.org/ | sh` should setup the initial server.
