### ISSUE TITLE
Deploy buttons in Readme

### ISSUE THREAD

**Issue by hoodwink73** [LibreRead/install#6]
Since it is a self-hosted project, will it make sense to add [Deploy to Now](https://deploy.now.sh) or [Deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button) buttons in the readme?

I am not familiar with the deployment strategies used in the repo but I think I can use the docker files to create one-click deployments to the above-mentioned platforms.

If you think this to be useful, I can give it a try and raise a PR.

**Comment by mysticmode** [comment]
Hi @hoodwink73 Sorry for late reply, it was nice meeting you in kodai :yum:

Not sure about Heroku, but now.sh doesn't support `docker-compose` [so far](https://github.com/zeit/now-cli/issues/294). We need that compose files for installing redis(necessary) and elasticsearch(optional) services.

But if you see that we can do this with Heroku one-click deployment, that would be great!

Currently this repo is deprecated (sorry for the inconvenience). so feel free to make an issue and PR in the [server](https://github.com/LibreRead/server) repo.

Thank you!

**Comment by hoodwink73** [comment]
Cool. I will take a look. Thanks.
